package main

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// TestDocsCommandsRegenIsStable is the PRD #144 slice 10 drift guard
// for the per-subcommand reference pages under docs/commands/. The
// generator (`make docs-commands`) renders the pages from the Command
// Registry's `Long` strings; if a contributor hand-edits a generated
// page without updating the `Long` source, the next regen silently
// overwrites the hand-edit. This test makes that drift fail CI loudly.
//
// Mechanism: snapshot the committed `docs/commands/*.md` pages and
// `docs/commands.md` index, run `make docs-commands`, then compare
// the regenerated bytes against the snapshot. A mismatch means the
// committed pages disagree with a fresh regeneration — either a
// `Long` change without a regen, or a hand-edit without a matching
// source update. The cleanup restores the snapshot so the test is
// side-effect-free on the developer's working tree.
//
// The test SKIPs (does not fail) when `make` or `node` are
// unavailable: the docs regen pipeline depends on a Node toolchain
// that is not part of the Go test prerequisites. CI runs with both
// installed, so the skip never fires there.
func TestDocsCommandsRegenIsStable(t *testing.T) {
	// NOT t.Parallel(): mutates / regenerates the shared repo docs tree
	// (docs/commands*), so it must never overlap the sibling docs tests.
	for _, bin := range []string{"make", "node"} {
		if _, err := exec.LookPath(bin); err != nil {
			t.Skipf("docs regen requires %q on PATH: %v", bin, err)
		}
	}

	repoRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatalf("resolve repo root: %v", err)
	}
	docsDir := filepath.Join(repoRoot, "docs", "commands")
	indexPath := filepath.Join(repoRoot, "docs", "commands.md")
	snapshot := readDocsCommandsDir(t, docsDir)
	indexBefore, err := os.ReadFile(indexPath)
	if err != nil {
		t.Fatalf("read %s: %v", indexPath, err)
	}
	t.Cleanup(func() {
		restoreDocsCommandsDir(t, docsDir, snapshot)
		if err := os.WriteFile(indexPath, indexBefore, 0o644); err != nil {
			t.Fatalf("restore %s: %v", indexPath, err)
		}
	})

	regen := exec.Command("make", "docs-commands")
	regen.Dir = repoRoot
	if out, err := regen.CombinedOutput(); err != nil {
		t.Fatalf("`make docs-commands` failed: %v\n%s", err, out)
	}

	// Compare the regenerated pages against the snapshot. A drift
	// shows up as either a byte-mismatch on a shared name or a name
	// that exists in one set but not the other.
	regenerated := readDocsCommandsDir(t, docsDir)
	mismatches := compareDocsCommandsSnapshots(snapshot, regenerated)
	indexAfter, err := os.ReadFile(indexPath)
	if err != nil {
		t.Fatalf("read regenerated index: %v", err)
	}
	if !bytes.Equal(indexBefore, indexAfter) {
		mismatches = append(mismatches, "docs/commands.md")
	}
	if len(mismatches) > 0 {
		sort.Strings(mismatches)
		t.Fatalf("docs regen drift — committed pages disagree with `make docs-commands` output; rerun `make docs-commands` and commit the result.\nDrifted files:\n  %s", strings.Join(mismatches, "\n  "))
	}
}

// readDocsCommandsDir reads every *.md page under dir into a
// name→bytes map. Used both to capture the pre-regen snapshot (so
// the test cleanup can restore the working tree) and to read the
// regenerated pages for byte-comparison.
func readDocsCommandsDir(t *testing.T, dir string) map[string][]byte {
	t.Helper()
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read %s: %v", dir, err)
	}
	out := make(map[string][]byte, len(entries))
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		path := filepath.Join(dir, e.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		out[e.Name()] = data
	}
	return out
}

// compareDocsCommandsSnapshots returns a list of file names that
// differ between snap (the committed bytes) and got (the freshly
// regenerated bytes). Drift kinds reported: byte-mismatch on a name
// present in both; name missing from one side. Result is unsorted —
// the caller sorts for a stable failure message.
func compareDocsCommandsSnapshots(snap, got map[string][]byte) []string {
	var drift []string
	for name, want := range snap {
		have, ok := got[name]
		if !ok {
			drift = append(drift, name+" (missing after regen)")
			continue
		}
		if !bytes.Equal(want, have) {
			drift = append(drift, name)
		}
	}
	for name := range got {
		if _, ok := snap[name]; !ok {
			drift = append(drift, name+" (new after regen)")
		}
	}
	return drift
}

// restoreDocsCommandsDir writes the snapshot back, removing any files
// the regen created that were not present in the snapshot. The test
// must leave the working tree byte-identical to its starting state so
// a successful run is invisible to `git status`.
func restoreDocsCommandsDir(t *testing.T, dir string, snap map[string][]byte) {
	t.Helper()
	for name, data := range snap {
		path := filepath.Join(dir, name)
		if err := os.WriteFile(path, data, 0o644); err != nil {
			t.Fatalf("restore %s: %v", path, err)
		}
	}
	// Remove any file the regen wrote that was not in the snapshot.
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read %s during cleanup: %v", dir, err)
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		if _, ok := snap[e.Name()]; ok {
			continue
		}
		path := filepath.Join(dir, e.Name())
		if err := os.Remove(path); err != nil {
			t.Fatalf("cleanup %s: %v", path, err)
		}
	}
}
